from datetime import datetime

import pytz

from backend import models
from backend.db import db

operater = db.session.query(models.Operater).get(388)
komitent = db.session.query(models.Komitent).get(599)
firma = db.session.query(models.Firma).get(241)
naplatni_uredjaj = db.session.query(models.NaplatniUredjaj).get(252)
valuta = db.session.query(models.Valuta).get(50)
corrected_invoice = db.session.query(models.Faktura).get(2835324)

faktura = models.Faktura()
faktura.datumfakture = datetime.now(pytz.timezone('Europe/Podgorica'))
faktura.datumvalute = datetime.strptime('2023-07-23 17:22:42', "%Y-%m-%d %H:%M:%S")
faktura.status = 1
faktura.napomena = None
faktura.vrstaplacanja = None
faktura.vrstaplacanja_id = None
faktura.brojoperatera = operater.id
faktura.operater = operater
faktura.komitent_id = komitent.id
faktura.komitent = komitent
faktura.ukupna_cijena_osnovna = -283.152000
faktura.ukupna_cijena_rabatisana = -283.152000
faktura.ukupna_cijena_puna = -342.613900
faktura.ukupna_cijena_prodajna = -342.613900
faktura.porez_iznos = -59.461900
faktura.rabat_iznos_osnovni = 0
faktura.rabat_iznos_prodajni = 0
faktura.firma_id = firma.id
faktura.firma = firma
faktura.naplatni_uredjaj_id = naplatni_uredjaj.id
faktura.naplatni_uredjaj = naplatni_uredjaj
faktura.valuta_id = valuta.id
faktura.valuta = valuta
faktura.kurs_razmjene = 1
faktura.poreski_period = datetime.strptime('2023-07-29 19:28:09', "%Y-%m-%d %H:%M:%S")
faktura.ima_sacuvane_grupe_poreza = None
faktura.tip_fakture_id = models.Faktura.TYPE_ERROR_CORRECTIVE
faktura.lokacija_dokumenta = None
faktura.korigovana_ukupna_cijena_osnovna = None
faktura.korigovana_ukupna_cijena_rabatisana = None
faktura.korigovana_ukupna_cijena_puna = None
faktura.korigovana_ukupna_cijena_prodajna = None
faktura.korigovani_porez_iznos = None
faktura.korigovani_rabat_iznos_osnovni = 0
faktura.korigovani_rabat_iznos_prodajni = 0
faktura.datum_prometa = None
faktura.is_cash = 0
faktura.source_invoice_id = None
faktura.credit_note_turnover_used = 0
faktura.credit_note_turnover_remaining = -342.613900
faktura.tax_exemption_amount = 0
faktura.corrected_tax_exemption_amount = None
faktura.advance_invoice_id = None
faktura.corrective_advance_invoice_id = None
faktura.is_advance_invoice = None
faktura.korigovana_faktura = corrected_invoice

payment_method = models.PaymentMethod()
payment_method.payment_method_type_id = models.PaymentMethod.TYPE_ACCOUNT
payment_method.amount = -342.613900
faktura.payment_methods.append(payment_method)

stavka1 = models.FakturaStavka()
stavka1.sifra = 1
stavka1.kolicina = -5.340000
stavka1.jedinicna_cijena_osnovna = 24.800000
stavka1.jedinicna_cijena_rabatisana = 24.800000
stavka1.jedinicna_cijena_puna = 30.008000
stavka1.jedinicna_cijena_prodajna = 30.008000
stavka1.ukupna_cijena_osnovna = -132.432000
stavka1.ukupna_cijena_rabatisana = -132.432000
stavka1.ukupna_cijena_puna = -160.242700
stavka1.ukupna_cijena_prodajna = -160.242700
stavka1.porez_procenat = 21.000000
stavka1.porez_iznos = -27.810700
stavka1.rabat_procenat = 0.000000
stavka1.rabat_iznos_osnovni = 0.000000
stavka1.rabat_iznos_prodajni = 0.000000
stavka1.naziv = 'ROLO ZAVJESE - korekcija količine'
stavka1.jedinica_mjere_id = 215
stavka1.tax_exemption_reason_id = None
stavka1.magacin_zaliha_id = None
stavka1.korigovana_kolicina = None
stavka1.korigovana_ukupna_cijena_osnovna = None
stavka1.korigovana_ukupna_cijena_rabatisana = None
stavka1.korigovana_ukupna_cijena_puna = None
stavka1.korigovana_ukupna_cijena_prodajna = None
stavka1.korigovani_porez_iznos = None
stavka1.korigovani_rabat_iznos_osnovni = None
stavka1.korigovani_rabat_iznos_prodajni = None
stavka1.izvor_kalkulacije = 1
stavka1.credit_note_turnover_used = 0.000000
stavka1.credit_note_turnover_remaining = -160.242700
stavka1.tax_exemption_amount = 0.000000
stavka1.corrected_tax_exemption_amount = None
stavka1.corrected_invoice_item_id = 6902071
stavka1.correction_type_id = 1
stavka1.korigovana_jedinicna_cijena_osnovna = None
stavka1.korigovana_jedinicna_cijena_rabatisana = None
stavka1.korigovana_jedinicna_cijena_puna = None
stavka1.korigovana_jedinicna_cijena_prodajna = None
faktura.stavke.append(stavka1)

stavka2 = models.FakturaStavka()
stavka2.sifra = 1
stavka2.kolicina = -3.000000
stavka2.jedinicna_cijena_osnovna = 27.270000
stavka2.jedinicna_cijena_rabatisana = 27.270000
stavka2.jedinicna_cijena_puna = 32.996700
stavka2.jedinicna_cijena_prodajna = 32.996700
stavka2.ukupna_cijena_osnovna = -81.810000
stavka2.ukupna_cijena_rabatisana = -81.810000
stavka2.ukupna_cijena_puna = -98.990100
stavka2.ukupna_cijena_prodajna = -98.990100
stavka2.porez_procenat = 21.000000
stavka2.porez_iznos = -17.180100
stavka2.rabat_procenat = 0.000000
stavka2.rabat_iznos_osnovni = 0.000000
stavka2.rabat_iznos_prodajni = 0.000000
stavka2.naziv = 'CRNA BLACKOUT DRAPERIJA - korekcija količine'
stavka2.jedinica_mjere_id = 214
stavka2.tax_exemption_reason_id = None
stavka2.magacin_zaliha_id = None
stavka2.korigovana_kolicina = None
stavka2.korigovana_ukupna_cijena_osnovna = None
stavka2.korigovana_ukupna_cijena_rabatisana = None
stavka2.korigovana_ukupna_cijena_puna = None
stavka2.korigovana_ukupna_cijena_prodajna = None
stavka2.korigovani_porez_iznos = None
stavka2.korigovani_rabat_iznos_osnovni = None
stavka2.korigovani_rabat_iznos_prodajni = None
stavka2.izvor_kalkulacije = 1
stavka2.credit_note_turnover_used = 0.000000
stavka2.credit_note_turnover_remaining = -98.990100
stavka2.tax_exemption_amount = 0.000000
stavka2.corrected_tax_exemption_amount = None
stavka2.corrected_invoice_item_id = 6902072
stavka2.correction_type_id = 1
stavka2.korigovana_jedinicna_cijena_osnovna = None
stavka2.korigovana_jedinicna_cijena_rabatisana = None
stavka2.korigovana_jedinicna_cijena_puna = None
stavka2.korigovana_jedinicna_cijena_prodajna = None
faktura.stavke.append(stavka2)

stavka3 = models.FakturaStavka()
stavka3.sifra = 1
stavka3.kolicina = -1.500000
stavka3.jedinicna_cijena_osnovna = 8.260000
stavka3.jedinicna_cijena_rabatisana = 8.260000
stavka3.jedinicna_cijena_puna = 9.994600
stavka3.jedinicna_cijena_prodajna = 9.994600
stavka3.ukupna_cijena_osnovna = -12.390000
stavka3.ukupna_cijena_rabatisana = -12.390000
stavka3.ukupna_cijena_puna = -14.991900
stavka3.ukupna_cijena_prodajna = -14.991900
stavka3.porez_procenat = 21.000000
stavka3.porez_iznos = -2.601900
stavka3.rabat_procenat = 0.000000
stavka3.rabat_iznos_osnovni = 0.000000
stavka3.rabat_iznos_prodajni = 0.000000
stavka3.naziv = 'GARNISLA - korekcija količine'
stavka3.jedinica_mjere_id = 214
stavka3.tax_exemption_reason_id = None
stavka3.magacin_zaliha_id = None
stavka3.korigovana_kolicina = None
stavka3.korigovana_ukupna_cijena_osnovna = None
stavka3.korigovana_ukupna_cijena_rabatisana = None
stavka3.korigovana_ukupna_cijena_puna = None
stavka3.korigovana_ukupna_cijena_prodajna = None
stavka3.korigovani_porez_iznos = None
stavka3.korigovani_rabat_iznos_osnovni = None
stavka3.korigovani_rabat_iznos_prodajni = None
stavka3.izvor_kalkulacije = 1
stavka3.credit_note_turnover_used = 0.000000
stavka3.credit_note_turnover_remaining = -14.991900
stavka3.tax_exemption_amount = 0.000000
stavka3.corrected_tax_exemption_amount = None
stavka3.corrected_invoice_item_id = 6902073
stavka3.correction_type_id = 1
stavka3.korigovana_jedinicna_cijena_osnovna = None
stavka3.korigovana_jedinicna_cijena_rabatisana = None
stavka3.korigovana_jedinicna_cijena_puna = None
stavka3.korigovana_jedinicna_cijena_prodajna = None
faktura.stavke.append(stavka3)

stavka4 = models.FakturaStavka()
stavka4.sifra = 1
stavka4.kolicina = -1.800000
stavka4.jedinicna_cijena_osnovna = 27.270000
stavka4.jedinicna_cijena_rabatisana = 27.270000
stavka4.jedinicna_cijena_puna = 32.996700
stavka4.jedinicna_cijena_prodajna = 32.996700
stavka4.ukupna_cijena_osnovna = -49.086000
stavka4.ukupna_cijena_rabatisana = -49.086000
stavka4.ukupna_cijena_puna = -59.394100
stavka4.ukupna_cijena_prodajna = -59.394100
stavka4.porez_procenat = 21.000000
stavka4.porez_iznos = -10.308100
stavka4.rabat_procenat = 0.000000
stavka4.rabat_iznos_osnovni = 0.000000
stavka4.rabat_iznos_prodajni = 0.000000
stavka4.naziv = 'CRNA BLACKOUT DRAPERIJA - korekcija količine'
stavka4.jedinica_mjere_id = 214
stavka4.tax_exemption_reason_id = None
stavka4.magacin_zaliha_id = None
stavka4.korigovana_kolicina = None
stavka4.korigovana_ukupna_cijena_osnovna = None
stavka4.korigovana_ukupna_cijena_rabatisana = None
stavka4.korigovana_ukupna_cijena_puna = None
stavka4.korigovana_ukupna_cijena_prodajna = None
stavka4.korigovani_porez_iznos = None
stavka4.korigovani_rabat_iznos_osnovni = None
stavka4.korigovani_rabat_iznos_prodajni = None
stavka4.izvor_kalkulacije = 1
stavka4.credit_note_turnover_used = 0.000000
stavka4.credit_note_turnover_remaining = -59.394100
stavka4.tax_exemption_amount = 0.000000
stavka4.corrected_tax_exemption_amount = None
stavka4.corrected_invoice_item_id = 6902074
stavka4.correction_type_id = 1
stavka4.korigovana_jedinicna_cijena_osnovna = None
stavka4.korigovana_jedinicna_cijena_rabatisana = None
stavka4.korigovana_jedinicna_cijena_puna = None
stavka4.korigovana_jedinicna_cijena_prodajna = None
faktura.stavke.append(stavka4)

stavka5 = models.FakturaStavka()
stavka5.sifra = 1
stavka5.kolicina = -0.900000
stavka5.jedinicna_cijena_osnovna = 8.260000
stavka5.jedinicna_cijena_rabatisana = 8.260000
stavka5.jedinicna_cijena_puna = 9.994600
stavka5.jedinicna_cijena_prodajna = 9.994600
stavka5.ukupna_cijena_osnovna = -7.434000
stavka5.ukupna_cijena_rabatisana = -7.434000
stavka5.ukupna_cijena_puna = -8.995100
stavka5.ukupna_cijena_prodajna = -8.995100
stavka5.porez_procenat = 21.000000
stavka5.porez_iznos = -1.561100
stavka5.rabat_procenat = 0.000000
stavka5.rabat_iznos_osnovni = 0.000000
stavka5.rabat_iznos_prodajni = 0.000000
stavka5.naziv = 'GARNIŠLA - korekcija količine'
stavka5.jedinica_mjere_id = 214
stavka5.tax_exemption_reason_id = None
stavka5.magacin_zaliha_id = None
stavka5.korigovana_kolicina = None
stavka5.korigovana_ukupna_cijena_osnovna = None
stavka5.korigovana_ukupna_cijena_rabatisana = None
stavka5.korigovana_ukupna_cijena_puna = None
stavka5.korigovana_ukupna_cijena_prodajna = None
stavka5.korigovani_porez_iznos = None
stavka5.korigovani_rabat_iznos_osnovni = None
stavka5.korigovani_rabat_iznos_prodajni = None
stavka5.izvor_kalkulacije = 1
stavka5.credit_note_turnover_used = 0.000000
stavka5.credit_note_turnover_remaining = -8.995100
stavka5.tax_exemption_amount = 0.000000
stavka5.corrected_tax_exemption_amount = None
stavka5.corrected_invoice_item_id = 6902075
stavka5.correction_type_id = 1
stavka5.korigovana_jedinicna_cijena_osnovna = None
stavka5.korigovana_jedinicna_cijena_rabatisana = None
stavka5.korigovana_jedinicna_cijena_puna = None
stavka5.korigovana_jedinicna_cijena_prodajna = None
faktura.stavke.append(stavka5)

grupa_poreza1 = models.FakturaGrupaPoreza()
grupa_poreza1.broj_stavki = 5
grupa_poreza1.ukupna_cijena_osnovna = -283.152000
grupa_poreza1.ukupna_cijena_rabatisana = -283.152000
grupa_poreza1.ukupna_cijena_puna = -342.613900
grupa_poreza1.ukupna_cijena_prodajna = -342.613900
grupa_poreza1.porez_procenat = 21
grupa_poreza1.porez_iznos = -59.461900
grupa_poreza1.rabat_iznos_osnovni = 0
grupa_poreza1.rabat_iznos_prodajni = 0
grupa_poreza1.credit_note_turnover_remaining = -342.613900
grupa_poreza1.credit_note_turnover_used = 0
grupa_poreza1.tax_exemption_amount = 0
grupa_poreza1.tax_exemption_reason_id = None
grupa_poreza1.tax_exemption_reason = None
faktura.grupe_poreza.append(grupa_poreza1)

db.session.add(faktura)
db.session.commit()
