"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2023-12-24 03:59:32.467318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('korisnicko_ime', sa.String(length=200), nullable=True),
    sa.Column('lozinka', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_obrada',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('lokacija_ulaznih_csv_datoteka', sa.String(length=255), nullable=False),
    sa.Column('lokacija_neuspjelih_csv_datoteka', sa.String(length=255), nullable=False),
    sa.Column('lokacija_uspjelih_csv_datoteka', sa.String(length=255), nullable=False),
    sa.Column('lokacija_izlaznih_csv_datoteka', sa.String(length=255), nullable=False),
    sa.Column('lokacija_debug_datoteka', sa.String(length=255), nullable=False),
    sa.Column('format_datoteke', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('drzave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sifravalute', sa.Integer(), nullable=True),
    sa.Column('opisvalute', sa.String(length=3), nullable=True),
    sa.Column('drzava_skraceno_2', sa.String(length=2), nullable=True),
    sa.Column('drzava_skraceno_3', sa.String(length=3), nullable=True),
    sa.Column('drzava', sa.String(length=50), nullable=True),
    sa.Column('drzavaeng', sa.String(length=50), nullable=True),
    sa.Column('paritet', sa.Integer(), nullable=True),
    sa.Column('issepa', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faktura_tip',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('efi_kod', sa.String(length=50), nullable=True),
    sa.Column('je_aktivno', sa.Boolean(create_constraint=True, name='faktura_tip_chk_1'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_item_correction_type',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_method_type',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('efi_code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('is_cash', sa.Boolean(create_constraint=True, name='payment_method_type_chk_1'), nullable=True),
    sa.Column('sort_weight', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(create_constraint=True, name='payment_method_type_chk_2'), nullable=True),
    sa.Column('is_noncash', sa.Boolean(create_constraint=True, name='payment_method_type_chk_3'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poreska_stopa',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('procenat', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soap_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(create_constraint=True, name='soap_user_chk_1'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tax_exemption_reason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('efi_code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tip_identifikacione_oznake',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('naziv', sa.String(length=50), nullable=True),
    sa.Column('efi_kod', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valuta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv_me', sa.String(length=150), nullable=True),
    sa.Column('naziv_en', sa.String(length=150), nullable=True),
    sa.Column('iso_4217_numericki_kod', sa.String(length=3), nullable=True),
    sa.Column('iso_4217_alfanumericki_kod', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vrsta_placanja',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('kod', sa.String(length=30), nullable=True),
    sa.Column('naziv', sa.String(length=100), nullable=True),
    sa.Column('tip_naziv', sa.String(length=30), nullable=True),
    sa.Column('tip_kod', sa.String(length=30), nullable=True),
    sa.Column('je_aktivna', sa.Boolean(create_constraint=True, name='vrsta_placanja_chk_1'), nullable=False),
    sa.Column('sort_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=250), nullable=True),
    sa.Column('pib', sa.String(length=15), nullable=True),
    sa.Column('pdvbroj', sa.String(length=15), nullable=True),
    sa.Column('ziroracun', sa.Text(), nullable=True),
    sa.Column('je_poreski_obaveznik', sa.Boolean(), nullable=True),
    sa.Column('grad', sa.String(length=200), nullable=True),
    sa.Column('adresa', sa.Text(), nullable=True),
    sa.Column('drzava', sa.Integer(), nullable=True),
    sa.Column('telefon', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('logo_filepath', sa.String(length=255), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('ima_upload_dokumenta', sa.Boolean(create_constraint=True, name='firma_chk_1'), nullable=True),
    sa.Column('dokument_qr_code_x', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_qr_code_y', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_qr_code_width', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_qr_code_height', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_ikof_x', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_ikof_y', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_ikof_font_size', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_jikr_x', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_jikr_y', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_jikr_font_size', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_efi_verify_url_x', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_efi_verify_url_y', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_efi_verify_url_font_size', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_kod_operatera_x', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_kod_operatera_y', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('dokument_kod_operatera_font_size', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('je_aktivna', sa.Boolean(create_constraint=True, name='firma_chk_2'), nullable=True),
    sa.Column('certificate_password', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['drzava'], ['drzave.id'], name='firma_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('drzava', 'firma', ['drzava'], unique=False)
    op.create_table('komitent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=250), nullable=True),
    sa.Column('pib', sa.String(length=15), nullable=True),
    sa.Column('pdvbroj', sa.String(length=15), nullable=True),
    sa.Column('adresa', sa.Text(), nullable=True),
    sa.Column('telefon', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('ziroracun', sa.Text(), nullable=True),
    sa.Column('grad', sa.String(length=200), nullable=True),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('pibvlasnikapodatka', sa.String(length=15), nullable=True),
    sa.Column('je_komitent', sa.Boolean(create_constraint=True, name='komitent_chk_1'), nullable=True),
    sa.Column('je_dobavljac', sa.Boolean(create_constraint=True, name='komitent_chk_2'), nullable=True),
    sa.Column('drzava', sa.Integer(), nullable=True),
    sa.Column('tip_identifikacione_oznake_id', sa.Integer(), nullable=True),
    sa.Column('identifikaciona_oznaka', sa.String(length=100), nullable=True),
    sa.Column('show_total_debt', sa.Boolean(create_constraint=True, name='komitent_chk_3'), nullable=True),
    sa.Column('previous_debt', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['drzava'], ['drzave.id'], name='komitent_ibfk_1'),
    sa.ForeignKeyConstraint(['tip_identifikacione_oznake_id'], ['tip_identifikacione_oznake.id'], name='komitent_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_komitent_drzava'), 'komitent', ['drzava'], unique=False)
    op.create_index('tip_identifikacione_oznake_id', 'komitent', ['tip_identifikacione_oznake_id'], unique=False)
    op.create_table('company_settings',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('smtp_active', sa.Boolean(create_constraint=True, name='company_settings_chk_1'), nullable=True),
    sa.Column('smtp_host', sa.String(length=120), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('smtp_mail', sa.String(length=255), nullable=True),
    sa.Column('smtp_username', sa.String(length=255), nullable=True),
    sa.Column('smtp_password', sa.String(length=255), nullable=True),
    sa.Column('can_schedule', sa.Boolean(create_constraint=True, name='company_settings_chk_2'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['firma.id'], name='fk__company_settings__firma'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('csv_obrada_ovlascenje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('csv_obrada_id', sa.Integer(), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['csv_obrada_id'], ['csv_obrada.id'], name='fk__csv_obrada_ovlascenje__csv_obrada'),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='fk__csv_obrada_ovlascenje__firma'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dospjela_faktura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('period', sa.DateTime(), nullable=True),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=True),
    sa.Column('lokacija_dokumenta', sa.String(length=255), nullable=True),
    sa.Column('opis', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='dospjela_faktura_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firma_id', 'dospjela_faktura', ['firma_id'], unique=False)
    op.create_table('faktura_mail_kampanja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('datum_pocetka', sa.DateTime(), nullable=False),
    sa.Column('datum_zavrsetka', sa.DateTime(), nullable=False),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='fk__faktura_mail_kampanja__firma'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupa_artikala',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=True),
    sa.Column('ui_default', sa.Boolean(create_constraint=True, name='grupa_artikala_chk_1'), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('boja', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='grupa_artikala_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firma_id', 'grupa_artikala', ['firma_id'], unique=False)
    op.create_table('jedinica_mjere',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ui_default', sa.Boolean(create_constraint=True, name='jedinica_mjere_chk_1'), nullable=True),
    sa.Column('naziv', sa.String(length=15), nullable=True),
    sa.Column('opis', sa.String(length=255), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='jedinica_mjere_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firma_id', 'jedinica_mjere', ['firma_id'], unique=False)
    op.create_table('komitent_placanje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('komitent_id', sa.Integer(), nullable=True),
    sa.Column('iznos', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('datum_placanja', sa.DateTime(), nullable=False),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='fk__komitent_placanje__firma'),
    sa.ForeignKeyConstraint(['komitent_id'], ['komitent.id'], name='fk__komitent_placanje__komitent'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magacin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='magacin_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firma_id', 'magacin', ['firma_id'], unique=False)
    op.create_table('organizaciona_jedinica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('efi_kod', sa.String(length=10), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('adresa', sa.Text(), nullable=True),
    sa.Column('grad', sa.String(length=200), nullable=True),
    sa.Column('drzava_id', sa.Integer(), nullable=True),
    sa.Column('naziv', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['drzava_id'], ['drzave.id'], name='organizaciona_jedinica_ibfk_2'),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='organizaciona_jedinica_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('drzava_id', 'organizaciona_jedinica', ['drzava_id'], unique=False)
    op.create_index('firma_id', 'organizaciona_jedinica', ['firma_id'], unique=False)
    op.create_table('soap_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('soap_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['firma.id'], name='fk__soap_permission__firma'),
    sa.ForeignKeyConstraint(['soap_user_id'], ['soap_user.id'], name='fk__soap_permission__soap_user'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artikal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sifra', sa.String(length=50), nullable=True),
    sa.Column('barkod', sa.String(length=50), nullable=True),
    sa.Column('naziv', sa.Text(), nullable=True),
    sa.Column('opis', sa.Text(), nullable=True),
    sa.Column('grupa_artikala_id', sa.Integer(), nullable=True),
    sa.Column('jedinica_mjere_id', sa.Integer(), nullable=True),
    sa.Column('slika_filepath', sa.String(length=255), nullable=True),
    sa.Column('slika_filename', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['grupa_artikala_id'], ['grupa_artikala.id'], name='artikal_ibfk_1'),
    sa.ForeignKeyConstraint(['jedinica_mjere_id'], ['jedinica_mjere.id'], name='artikal_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('grupa_artikala_id', 'artikal', ['grupa_artikala_id'], unique=False)
    op.create_index('jedinica_mjere_id', 'artikal', ['jedinica_mjere_id'], unique=False)
    op.create_table('csv_datoteka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('putanja', sa.String(length=255), nullable=False),
    sa.Column('naziv', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=True),
    sa.Column('csv_upload_ovlascenje_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['csv_upload_ovlascenje_id'], ['csv_obrada_ovlascenje.id'], name='fk__cv_datoteka__csv_obrada_ovlascenje'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dospjela_faktura_notifikacija',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dospjela_faktura_id', sa.Integer(), nullable=True),
    sa.Column('operater_id', sa.Integer(), nullable=True),
    sa.Column('je_vidio', sa.Boolean(create_constraint=True, name='dospjela_faktura_notifikacija_chk_1'), nullable=True),
    sa.ForeignKeyConstraint(['dospjela_faktura_id'], ['dospjela_faktura.id'], name='fk__dospjela_faktura_notifikacija__dospjela_faktura'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magacin_redni_broj_kalkulacije',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magacin_id', sa.Integer(), nullable=False),
    sa.Column('godina', sa.Integer(), nullable=False),
    sa.Column('redni_broj', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['magacin_id'], ['magacin.id'], name='magacin_redni_broj_kalkulacije_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('magacin_id', 'magacin_redni_broj_kalkulacije', ['magacin_id'], unique=False)
    op.create_table('naplatni_uredjaj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('efi_kod', sa.String(length=10), nullable=True),
    sa.Column('organizaciona_jedinica_id', sa.Integer(), nullable=True),
    sa.Column('tip_naplatnog_uredjaja_id', sa.Integer(), nullable=False),
    sa.Column('podrazumijevani_iznos_depozita', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['organizaciona_jedinica_id'], ['organizaciona_jedinica.id'], name='naplatni_uredjaj_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('organizaciona_jedinica_id', 'naplatni_uredjaj', ['organizaciona_jedinica_id'], unique=False)
    op.create_table('organizational_unit_settings',
    sa.Column('organizational_unit_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('default_invoice_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organizational_unit_id'], ['organizaciona_jedinica.id'], name='FK_8CA97D54D662'),
    sa.PrimaryKeyConstraint('organizational_unit_id')
    )
    op.create_table('credit_note_processing_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['naplatni_uredjaj.id'], name='credit_note_processing_lock_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firma_redni_broj_fakture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('godina', sa.Integer(), nullable=True),
    sa.Column('poslednja_faktura_redni_broj_fakture', sa.Integer(), nullable=True),
    sa.Column('naplatni_uredjaj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['naplatni_uredjaj_id'], ['naplatni_uredjaj.id'], name='firma_redni_broj_fakture_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('naplatni_uredjaj_id', 'firma_redni_broj_fakture', ['naplatni_uredjaj_id'], unique=False)
    op.create_index('poslednja_faktura_redni_broj_fakture', 'firma_redni_broj_fakture', ['poslednja_faktura_redni_broj_fakture'], unique=False)
    op.create_table('invoice_counter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('payment_device_id', sa.Integer(), nullable=True),
    sa.Column('invoice_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_type_id'], ['faktura_tip.id'], name='FK_52EFAE01A4AB'),
    sa.ForeignKeyConstraint(['payment_device_id'], ['naplatni_uredjaj.id'], name='FK_EC290607829E'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_processing_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['naplatni_uredjaj.id'], name='fk__payment_device_lock__naplatni_uredjaj'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knjizno_odobrenje_redni_broj',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('godina', sa.Integer(), nullable=True),
    sa.Column('vrijednost', sa.Integer(), nullable=True),
    sa.Column('naplatni_uredjaj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['naplatni_uredjaj_id'], ['naplatni_uredjaj.id'], name='fk__knjizno_odobrenje_redni_broj__naplatni_uredjaj'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magacin_zaliha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('magacin_id', sa.Integer(), nullable=True),
    sa.Column('artikal_id', sa.Integer(), nullable=True),
    sa.Column('jedinicna_cijena_osnovna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('jedinicna_cijena_puna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('raspoloziva_kolicina', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('izvor_kalkulacije', sa.Integer(), nullable=True),
    sa.Column('porez_procenat', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('tax_exemption_reason_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artikal_id'], ['artikal.id'], name='magacin_zaliha_ibfk_2'),
    sa.ForeignKeyConstraint(['magacin_id'], ['magacin.id'], name='magacin_zaliha_ibfk_1'),
    sa.ForeignKeyConstraint(['tax_exemption_reason_id'], ['tax_exemption_reason.id'], name='FK_AF58CDCBEE5B'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('artikal_id', 'magacin_zaliha', ['artikal_id'], unique=False)
    op.create_index('magacin_id', 'magacin_zaliha', ['magacin_id'], unique=False)
    op.create_table('operater',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ime', sa.String(length=100), nullable=True),
    sa.Column('lozinka', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('kodoperatera', sa.String(length=10), nullable=True),
    sa.Column('admin', sa.Integer(), nullable=True),
    sa.Column('aktivan', sa.Integer(), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('magacin_id', sa.Integer(), nullable=True),
    sa.Column('naplatni_uredjaj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='operater_ibfk_1'),
    sa.ForeignKeyConstraint(['magacin_id'], ['magacin.id'], name='operater_ibfk_2'),
    sa.ForeignKeyConstraint(['naplatni_uredjaj_id'], ['naplatni_uredjaj.id'], name='operater_ibfk_3'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firma_id', 'operater', ['firma_id'], unique=False)
    op.create_index('magacin_id', 'operater', ['magacin_id'], unique=False)
    op.create_index('naplatni_uredjaj_id', 'operater', ['naplatni_uredjaj_id'], unique=False)
    op.create_table('order_grupa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naziv', sa.String(length=200), nullable=False),
    sa.Column('naplatni_uredjaj_id', sa.Integer(), nullable=False),
    sa.Column('komitent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['komitent_id'], ['komitent.id'], name='fk__order_grupa__komitent'),
    sa.ForeignKeyConstraint(['naplatni_uredjaj_id'], ['naplatni_uredjaj.id'], name='fk__order_grupa__naplatni_uredjaj'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_device_lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['naplatni_uredjaj.id'], name='FK_E8A750A4AC78'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faktura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=True),
    sa.Column('redni_broj_fakture', sa.Integer(), nullable=True),
    sa.Column('datumfakture', sa.DateTime(), nullable=True),
    sa.Column('datumvalute', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('vrstaplacanja', sa.Integer(), nullable=True),
    sa.Column('brojoperatera', sa.Integer(), nullable=True),
    sa.Column('komitent_id', sa.Integer(), nullable=True),
    sa.Column('ukupna_cijena_osnovna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_rabatisana', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_puna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_prodajna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('porez_iznos', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('rabat_iznos_osnovni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('rabat_iznos_prodajni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('efi_broj_fakture', sa.String(length=1000), nullable=True),
    sa.Column('efi_verify_url', sa.String(length=1000), nullable=True),
    sa.Column('ikof', sa.String(length=1000), nullable=True),
    sa.Column('jikr', sa.String(length=1000), nullable=True),
    sa.Column('iic', sa.String(length=32), nullable=True),
    sa.Column('xml_request', sa.Text(), nullable=True),
    sa.Column('xml_response', sa.Text(), nullable=True),
    sa.Column('storno_faktura_id', sa.Integer(), nullable=True),
    sa.Column('naplatni_uredjaj_id', sa.Integer(), nullable=True),
    sa.Column('valuta_id', sa.Integer(), nullable=True),
    sa.Column('kurs_razmjene', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('poreski_period', sa.DateTime(), nullable=True),
    sa.Column('tip_fakture_id', sa.Integer(), nullable=False),
    sa.Column('lokacija_dokumenta', sa.String(length=255), nullable=True),
    sa.Column('korigovana_ukupna_cijena_osnovna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_ukupna_cijena_rabatisana', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_ukupna_cijena_puna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_ukupna_cijena_prodajna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovani_porez_iznos', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovani_rabat_iznos_osnovni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovani_rabat_iznos_prodajni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('datum_prometa', sa.DateTime(), nullable=True),
    sa.Column('is_cash', sa.Boolean(create_constraint=True, name='faktura_chk_2'), nullable=True),
    sa.Column('source_invoice_id', sa.Integer(), nullable=True),
    sa.Column('credit_note_turnover_used', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('credit_note_turnover_remaining', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('tax_exemption_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('corrected_tax_exemption_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('advance_invoice_id', sa.Integer(), nullable=True),
    sa.Column('corrective_advance_invoice_id', sa.Integer(), nullable=True),
    sa.Column('is_advance_invoice', sa.Boolean(), nullable=True),
    sa.Column('error_corrective_invoice_id', sa.Integer(), nullable=True),
    sa.Column('customer_invoice_view', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advance_invoice_id'], ['faktura.id'], name='FK_CBDCC72AEA2D'),
    sa.ForeignKeyConstraint(['brojoperatera'], ['operater.id'], name='faktura_ibfk_2'),
    sa.ForeignKeyConstraint(['corrective_advance_invoice_id'], ['faktura.id'], name='FK_660E715072A8'),
    sa.ForeignKeyConstraint(['error_corrective_invoice_id'], ['faktura.id'], name='FK_D99A2890FCA6'),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='faktura_ibfk_4'),
    sa.ForeignKeyConstraint(['komitent_id'], ['komitent.id'], name='faktura_ibfk_3'),
    sa.ForeignKeyConstraint(['naplatni_uredjaj_id'], ['naplatni_uredjaj.id'], name='faktura_ibfk_6'),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['faktura.id'], name='FK_CF286C39278F'),
    sa.ForeignKeyConstraint(['storno_faktura_id'], ['faktura.id'], name='fk__faktura__storno_faktura'),
    sa.ForeignKeyConstraint(['tip_fakture_id'], ['faktura_tip.id'], name='fk__faktura__tip_fakture'),
    sa.ForeignKeyConstraint(['valuta_id'], ['valuta.id'], name='fk__faktura__valuta'),
    sa.ForeignKeyConstraint(['vrstaplacanja'], ['vrsta_placanja.id'], name='faktura_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IX_6D851962D0F8', 'faktura', ['firma_id', 'iic'], unique=False)
    op.create_index('IX_AB073009DB3F', 'faktura', ['customer_invoice_view'], unique=False)
    op.create_index('IX_D5DC1D3EFF98', 'faktura', ['naplatni_uredjaj_id', 'customer_invoice_view'], unique=False)
    op.create_index('IX_DDEF1ED69C9E', 'faktura', ['iic'], unique=False)
    op.create_index('brojoperatera', 'faktura', ['brojoperatera'], unique=False)
    op.create_index('firma_id', 'faktura', ['firma_id'], unique=False)
    op.create_index(op.f('ix_faktura_komitent_id'), 'faktura', ['komitent_id'], unique=False)
    op.create_index('naplatni_uredjaj_id', 'faktura', ['naplatni_uredjaj_id'], unique=False)
    op.create_index('storno_faktura_id', 'faktura', ['storno_faktura_id'], unique=False)
    op.create_index('vrstaplacanja', 'faktura', ['vrstaplacanja'], unique=False)
    op.create_table('kalkulacija',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broj_ulazne_fakture', sa.String(length=50), nullable=True),
    sa.Column('redni_broj_kalkulacije', sa.Integer(), nullable=True),
    sa.Column('datum_kalkulacije', sa.DateTime(), nullable=True),
    sa.Column('datum_ulazne_fakture', sa.DateTime(), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('dobavljac_id', sa.Integer(), nullable=True),
    sa.Column('operater_id', sa.Integer(), nullable=True),
    sa.Column('magacin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dobavljac_id'], ['komitent.id'], name='kalkulacija_ibfk_2'),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='kalkulacija_ibfk_1'),
    sa.ForeignKeyConstraint(['magacin_id'], ['magacin.id'], name='kalkulacija_ibfk_4'),
    sa.ForeignKeyConstraint(['operater_id'], ['operater.id'], name='kalkulacija_ibfk_3'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('dobavljac_id', 'kalkulacija', ['dobavljac_id'], unique=False)
    op.create_index('firma_id', 'kalkulacija', ['firma_id'], unique=False)
    op.create_index('magacin_id', 'kalkulacija', ['magacin_id'], unique=False)
    op.create_index('operater_id', 'kalkulacija', ['operater_id'], unique=False)
    op.create_table('knjizno_odobrenje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('redni_broj', sa.Integer(), nullable=True),
    sa.Column('datum_fiskalizacije', sa.DateTime(), nullable=True),
    sa.Column('datum_valute', sa.DateTime(), nullable=False),
    sa.Column('datum_prometa', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.String(length=100), nullable=True),
    sa.Column('vrsta_placanja_id', sa.Integer(), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=False),
    sa.Column('komitent_id', sa.Integer(), nullable=False),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=True),
    sa.Column('operater_id', sa.Integer(), nullable=True),
    sa.Column('naplatni_uredjaj_id', sa.Integer(), nullable=True),
    sa.Column('efi_broj_fakture', sa.String(length=1000), nullable=True),
    sa.Column('efi_verify_url', sa.String(length=1000), nullable=True),
    sa.Column('ikof', sa.String(length=1000), nullable=True),
    sa.Column('jikr', sa.String(length=1000), nullable=True),
    sa.Column('iic', sa.String(length=32), nullable=True),
    sa.Column('poreski_period', sa.DateTime(), nullable=True),
    sa.Column('valuta_id', sa.Integer(), nullable=True),
    sa.Column('kurs_razmjene', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('xml_request', sa.Text(), nullable=True),
    sa.Column('xml_response', sa.Text(), nullable=True),
    sa.Column('napomena', sa.Text(), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_amount_with_tax', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('discount_amount_with_tax', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_and_discount_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_and_discount_amount_with_tax', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='fk__knjizno_odobrenje__firma'),
    sa.ForeignKeyConstraint(['komitent_id'], ['komitent.id'], name='fk__knjizno_odobrenje__komitent'),
    sa.ForeignKeyConstraint(['naplatni_uredjaj_id'], ['naplatni_uredjaj.id'], name='fk__knjizno_odobrenje__naplatni_uredjaj'),
    sa.ForeignKeyConstraint(['operater_id'], ['operater.id'], name='fk__knjizno_odobrenje__operater'),
    sa.ForeignKeyConstraint(['valuta_id'], ['valuta.id'], name='fk__knjizno_odobrenje__valuta'),
    sa.ForeignKeyConstraint(['vrsta_placanja_id'], ['vrsta_placanja.id'], name='fk__knjizno_odobrenje__vrsta_placanja'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podesavanja_aplikacije',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pocetna_stranica', sa.String(length=100), nullable=True),
    sa.Column('operater_id', sa.Integer(), nullable=True),
    sa.Column('podrazumijevani_tip_unosa_stavke_fakture', sa.String(length=20), nullable=True),
    sa.Column('podrazumijevani_tip_stampe', sa.String(length=10), nullable=True),
    sa.Column('vidi_dospjele_fakture', sa.Boolean(create_constraint=True, name='podesavanja_aplikacije_chk_1'), nullable=True),
    sa.ForeignKeyConstraint(['operater_id'], ['operater.id'], name='podesavanja_aplikacije_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('operater_id', 'podesavanja_aplikacije', ['operater_id'], unique=False)
    op.create_table('smjena',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_pocetka', sa.DateTime(), nullable=True),
    sa.Column('datum_zavrsetka', sa.DateTime(), nullable=True),
    sa.Column('operater_id', sa.Integer(), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='smjena_ibfk_2'),
    sa.ForeignKeyConstraint(['operater_id'], ['operater.id'], name='smjena_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firma_id', 'smjena', ['firma_id'], unique=False)
    op.create_index('operater_id', 'smjena', ['operater_id'], unique=False)
    op.create_table('corrected_to_corrective',
    sa.Column('corrected_invoice_id', sa.Integer(), nullable=True),
    sa.Column('corrective_invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corrected_invoice_id'], ['faktura.id'], name='FK_C0AA1A13E759'),
    sa.ForeignKeyConstraint(['corrective_invoice_id'], ['faktura.id'], name='FK_E452FA82FFCA')
    )
    op.create_table('credit_note_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('knjizno_odobrenje_id', sa.Integer(), nullable=True),
    sa.Column('faultcode', sa.String(length=255), nullable=True),
    sa.Column('faultstring', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['knjizno_odobrenje_id'], ['knjizno_odobrenje.id'], name='fk__credit_note_response__knjizno_odobrenje'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_note_to_corrective_invoice',
    sa.Column('credit_note_id', sa.Integer(), nullable=True),
    sa.Column('corrective_invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corrective_invoice_id'], ['faktura.id'], name='FK_B16CB51CBC51'),
    sa.ForeignKeyConstraint(['credit_note_id'], ['knjizno_odobrenje.id'], name='FK_D8F870A18E90')
    )
    op.create_table('csv_obrada_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opis', sa.Text(), nullable=False),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=True),
    sa.Column('csv_datoteka_id', sa.Integer(), nullable=False),
    sa.Column('faktura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['csv_datoteka_id'], ['csv_datoteka.id'], name='fk__csv_obrada_log__csv_datoteka'),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktura.id'], name='fk__csv_obrada_log__faktura'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depozit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_slanja', sa.DateTime(), nullable=True),
    sa.Column('iznos', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.Column('operater_id', sa.Integer(), nullable=True),
    sa.Column('smjena_id', sa.Integer(), nullable=True),
    sa.Column('je_pocetak_dana', sa.Boolean(create_constraint=True, name='depozit_chk_1'), nullable=True),
    sa.Column('tip_depozita', sa.Integer(), nullable=True),
    sa.Column('fiskalizacioni_kod', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=True),
    sa.Column('naplatni_uredjaj_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['firma.id'], name='depozit_ibfk_1'),
    sa.ForeignKeyConstraint(['naplatni_uredjaj_id'], ['naplatni_uredjaj.id'], name='depozit_ibfk_4'),
    sa.ForeignKeyConstraint(['operater_id'], ['operater.id'], name='depozit_ibfk_2'),
    sa.ForeignKeyConstraint(['smjena_id'], ['smjena.id'], name='depozit_ibfk_3'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('firma_id', 'depozit', ['firma_id'], unique=False)
    op.create_index('naplatni_uredjaj_id', 'depozit', ['naplatni_uredjaj_id'], unique=False)
    op.create_index('operater_id', 'depozit', ['operater_id'], unique=False)
    op.create_index('smjena_id', 'depozit', ['smjena_id'], unique=False)
    op.create_table('faktura_grupa_poreza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broj_stavki', sa.Integer(), nullable=True),
    sa.Column('ukupna_cijena_osnovna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_rabatisana', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_puna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_prodajna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('porez_procenat', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('porez_iznos', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('rabat_iznos_osnovni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('rabat_iznos_prodajni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('faktura_id', sa.Integer(), nullable=True),
    sa.Column('credit_note_turnover_used', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('credit_note_turnover_remaining', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('tax_exemption_reason_id', sa.Integer(), nullable=True),
    sa.Column('tax_exemption_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktura.id'], name='fk__faktura_grupa_poreza__faktura'),
    sa.ForeignKeyConstraint(['tax_exemption_reason_id'], ['tax_exemption_reason.id'], name='FK_8BAFBAF29EDA'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faktura_mail_kampanja_stavka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faktura_mail_kampanja_id', sa.Integer(), nullable=True),
    sa.Column('komitent_id', sa.Integer(), nullable=False),
    sa.Column('faktura_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('mail_from', sa.String(length=255), nullable=False),
    sa.Column('mail_to', sa.String(length=255), nullable=False),
    sa.Column('opis_greske', sa.String(length=500), nullable=True),
    sa.Column('datum_slanja', sa.DateTime(), nullable=True),
    sa.Column('datum_kreiranja', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktura.id'], name='fk__faktura_mail_kampanja_stavka__faktura'),
    sa.ForeignKeyConstraint(['faktura_mail_kampanja_id'], ['faktura_mail_kampanja.id'], name='fk__faktura_mail_kampanja_stavka__faktura_mail_kampanja'),
    sa.ForeignKeyConstraint(['komitent_id'], ['komitent.id'], name='fk__faktura_mail_kampanja_stavka__komitent'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faktura_stavka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faktura_id', sa.Integer(), nullable=True),
    sa.Column('sifra', sa.String(length=50), nullable=True),
    sa.Column('kolicina', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('jedinicna_cijena_osnovna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('jedinicna_cijena_rabatisana', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('jedinicna_cijena_puna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('jedinicna_cijena_prodajna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_osnovna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_rabatisana', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_puna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('ukupna_cijena_prodajna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('porez_procenat', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('porez_iznos', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('rabat_procenat', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('rabat_iznos_osnovni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('rabat_iznos_prodajni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('naziv', sa.Text(), nullable=True),
    sa.Column('jedinica_mjere_id', sa.Integer(), nullable=True),
    sa.Column('tax_exemption_reason_id', sa.Integer(), nullable=True),
    sa.Column('magacin_zaliha_id', sa.Integer(), nullable=True),
    sa.Column('korigovana_kolicina', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_ukupna_cijena_osnovna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_ukupna_cijena_rabatisana', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_ukupna_cijena_puna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_ukupna_cijena_prodajna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovani_porez_iznos', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovani_rabat_iznos_osnovni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovani_rabat_iznos_prodajni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('izvor_kalkulacije', sa.Integer(), nullable=True),
    sa.Column('credit_note_turnover_used', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('credit_note_turnover_remaining', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('tax_exemption_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('corrected_tax_exemption_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('corrected_invoice_item_id', sa.Integer(), nullable=True),
    sa.Column('correction_type_id', sa.Integer(), nullable=True),
    sa.Column('korigovana_jedinicna_cijena_osnovna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_jedinicna_cijena_rabatisana', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_jedinicna_cijena_puna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('korigovana_jedinicna_cijena_prodajna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['corrected_invoice_item_id'], ['faktura_stavka.id'], name='FK_9D49FAE3C64E'),
    sa.ForeignKeyConstraint(['correction_type_id'], ['invoice_item_correction_type.id'], name='FK_A9D722C0C26F'),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktura.id'], name='faktura_stavka_ibfk_1'),
    sa.ForeignKeyConstraint(['jedinica_mjere_id'], ['jedinica_mjere.id'], name='faktura_stavka_ibfk_2'),
    sa.ForeignKeyConstraint(['magacin_zaliha_id'], ['magacin_zaliha.id'], name='faktura_stavka_ibfk_4'),
    sa.ForeignKeyConstraint(['tax_exemption_reason_id'], ['tax_exemption_reason.id'], name='FK_EDF2B661779B'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('faktura_id', 'faktura_stavka', ['faktura_id'], unique=False)
    op.create_index('jedinica_mjere_id', 'faktura_stavka', ['jedinica_mjere_id'], unique=False)
    op.create_index('magacin_zaliha_id', 'faktura_stavka', ['magacin_zaliha_id'], unique=False)
    op.create_table('faktura_veza',
    sa.Column('faktura_roditelj_id', sa.Integer(), nullable=True),
    sa.Column('faktura_dijete_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faktura_dijete_id'], ['faktura.id'], name='fk__faktura_veza__faktura_dijete_id'),
    sa.ForeignKeyConstraint(['faktura_roditelj_id'], ['faktura.id'], name='fk__faktura_veza__faktura_roditelj_id')
    )
    op.create_table('invoice_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_invoice_id', sa.Integer(), nullable=True),
    sa.Column('frequency_interval', sa.Integer(), nullable=True),
    sa.Column('frequency_type', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=True),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_run_datetime', sa.DateTime(), nullable=True),
    sa.Column('next_run_datetime', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(create_constraint=True, name='invoice_schedule_chk_1'), nullable=True),
    sa.Column('operater_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operater_id'], ['operater.id'], name='FK_8AE59688B892'),
    sa.ForeignKeyConstraint(['source_invoice_id'], ['faktura.id'], name='fk__invoice_schedule__faktura'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kalkulacija_stavka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kalkulacija_id', sa.Integer(), nullable=True),
    sa.Column('artikal_id', sa.Integer(), nullable=True),
    sa.Column('kolicina', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['artikal_id'], ['artikal.id'], name='kalkulacija_stavka_ibfk_2'),
    sa.ForeignKeyConstraint(['kalkulacija_id'], ['kalkulacija.id'], name='kalkulacija_stavka_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('artikal_id', 'kalkulacija_stavka', ['artikal_id'], unique=False)
    op.create_index('kalkulacija_id', 'kalkulacija_stavka', ['kalkulacija_id'], unique=False)
    op.create_table('knjizno_odobrenje_grupa_poreza',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broj_stavki', sa.Integer(), nullable=True),
    sa.Column('knjizno_odobrenje_id', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_amount_with_tax', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('discount_amount_with_tax', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_and_discount_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_and_discount_amount_with_tax', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.ForeignKeyConstraint(['knjizno_odobrenje_id'], ['knjizno_odobrenje.id'], name='fk__knjizno_odobrenje_grupa_poreza__knjizno_odobrenje'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knjizno_odobrenje_stavka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knjizno_odobrenje_id', sa.Integer(), nullable=False),
    sa.Column('fakture_ukupna_cijena_osnovna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('fakture_ukupna_cijena_rabatisana', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('fakture_ukupna_cijena_prodajna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('fakture_ukupna_cijena_puna', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('fakture_porez_iznos', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('fakture_rabat_iznos_osnovni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('fakture_rabat_iznos_prodajni', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('return_amount_with_tax', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('discount_amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('discount_amount_with_tax', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['knjizno_odobrenje_id'], ['knjizno_odobrenje.id'], name='fk__knjizno_odobrenje_stavka__knjizno_odobrenje'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_grupa_stavka',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_grupa_id', sa.Integer(), nullable=False),
    sa.Column('faktura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktura.id'], name='fk__order_grupa_stavka__faktura'),
    sa.ForeignKeyConstraint(['order_grupa_id'], ['order_grupa.id'], name='fk__order_grupa_stavka__order_grupa'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_type_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('advance_invoice_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['advance_invoice_id'], ['faktura.id'], name='fk__payment_method__advance_faktura'),
    sa.ForeignKeyConstraint(['invoice_id'], ['faktura.id'], name='fk__payment_method__faktura'),
    sa.ForeignKeyConstraint(['payment_method_type_id'], ['payment_method_type.id'], name='fk__payment_method_type__payment_method'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register_invoice_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('faktura_id', sa.Integer(), nullable=True),
    sa.Column('faultcode', sa.String(length=255), nullable=True),
    sa.Column('faultstring', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktura.id'], name='register_invoice_response_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('faktura_id', 'register_invoice_response', ['faktura_id'], unique=False)
    op.create_table('veza_knjizno_odobrenje_faktura',
    sa.Column('knjizno_odobrenje_id', sa.Integer(), nullable=False),
    sa.Column('faktura_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktura.id'], name='fk__veza_knjizno_odobrenje_faktura__faktura'),
    sa.ForeignKeyConstraint(['knjizno_odobrenje_id'], ['knjizno_odobrenje.id'], name='fk__veza_knjizno_odobrenje_faktura__knjizno_odobrenje')
    )
    op.create_table('veza_korektivna_faktura',
    sa.Column('korigovana_faktura_id', sa.Integer(), nullable=True),
    sa.Column('korektivna_faktura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['korektivna_faktura_id'], ['faktura.id'], name='fk__veza_korektivna_faktura__korektivna_faktura'),
    sa.ForeignKeyConstraint(['korigovana_faktura_id'], ['faktura.id'], name='fk__veza_korektivna_faktura__korigovana_faktura')
    )
    op.create_table('veza_zbirna_faktura',
    sa.Column('zbirna_faktura_id', sa.Integer(), nullable=True),
    sa.Column('clanica_faktura_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clanica_faktura_id'], ['faktura.id'], name='fk__veza_zbirna_faktura__clanica_faktura'),
    sa.ForeignKeyConstraint(['zbirna_faktura_id'], ['faktura.id'], name='fk__veza_zbirna_faktura__zbirna_faktura')
    )
    op.create_table('credit_note_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('knjizno_odobrenje_id', sa.Integer(), nullable=True),
    sa.Column('credit_note_response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['credit_note_response_id'], ['credit_note_response.id'], name='fk__credit_note_request__credit_note_response'),
    sa.ForeignKeyConstraint(['knjizno_odobrenje_id'], ['knjizno_odobrenje.id'], name='fk__credit_note_request__knjizno_odobrenje'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('register_deposit_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('depozit_id', sa.Integer(), nullable=True),
    sa.Column('faultcode', sa.String(length=255), nullable=True),
    sa.Column('faultstring', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['depozit_id'], ['depozit.id'], name='register_deposit_response_ibfk_1'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('depozit_id', 'register_deposit_response', ['depozit_id'], unique=False)
    op.create_table('register_invoice_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=255), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('faktura_id', sa.Integer(), nullable=True),
    sa.Column('register_invoice_response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktura.id'], name='register_invoice_request_ibfk_1'),
    sa.ForeignKeyConstraint(['register_invoice_response_id'], ['register_invoice_response.id'], name='register_invoice_request_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('faktura_id', 'register_invoice_request', ['faktura_id'], unique=False)
    op.create_index('register_invoice_response_id', 'register_invoice_request', ['register_invoice_response_id'], unique=False)
    op.create_table('register_deposit_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=50), nullable=True),
    sa.Column('xml', sa.Text(), nullable=True),
    sa.Column('depozit_id', sa.Integer(), nullable=True),
    sa.Column('register_deposit_response_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['depozit_id'], ['depozit.id'], name='register_deposit_request_ibfk_1'),
    sa.ForeignKeyConstraint(['register_deposit_response_id'], ['register_deposit_response.id'], name='register_deposit_request_ibfk_2'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('depozit_id', 'register_deposit_request', ['depozit_id'], unique=False)
    op.create_index('register_deposit_response_id', 'register_deposit_request', ['register_deposit_response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('register_deposit_response_id', table_name='register_deposit_request')
    op.drop_index('depozit_id', table_name='register_deposit_request')
    op.drop_table('register_deposit_request')
    op.drop_index('register_invoice_response_id', table_name='register_invoice_request')
    op.drop_index('faktura_id', table_name='register_invoice_request')
    op.drop_table('register_invoice_request')
    op.drop_index('depozit_id', table_name='register_deposit_response')
    op.drop_table('register_deposit_response')
    op.drop_table('credit_note_request')
    op.drop_table('veza_zbirna_faktura')
    op.drop_table('veza_korektivna_faktura')
    op.drop_table('veza_knjizno_odobrenje_faktura')
    op.drop_index('faktura_id', table_name='register_invoice_response')
    op.drop_table('register_invoice_response')
    op.drop_table('payment_method')
    op.drop_table('order_grupa_stavka')
    op.drop_table('knjizno_odobrenje_stavka')
    op.drop_table('knjizno_odobrenje_grupa_poreza')
    op.drop_index('kalkulacija_id', table_name='kalkulacija_stavka')
    op.drop_index('artikal_id', table_name='kalkulacija_stavka')
    op.drop_table('kalkulacija_stavka')
    op.drop_table('invoice_schedule')
    op.drop_table('faktura_veza')
    op.drop_index('magacin_zaliha_id', table_name='faktura_stavka')
    op.drop_index('jedinica_mjere_id', table_name='faktura_stavka')
    op.drop_index('faktura_id', table_name='faktura_stavka')
    op.drop_table('faktura_stavka')
    op.drop_table('faktura_mail_kampanja_stavka')
    op.drop_table('faktura_grupa_poreza')
    op.drop_index('smjena_id', table_name='depozit')
    op.drop_index('operater_id', table_name='depozit')
    op.drop_index('naplatni_uredjaj_id', table_name='depozit')
    op.drop_index('firma_id', table_name='depozit')
    op.drop_table('depozit')
    op.drop_table('csv_obrada_log')
    op.drop_table('credit_note_to_corrective_invoice')
    op.drop_table('credit_note_response')
    op.drop_table('corrected_to_corrective')
    op.drop_index('operater_id', table_name='smjena')
    op.drop_index('firma_id', table_name='smjena')
    op.drop_table('smjena')
    op.drop_index('operater_id', table_name='podesavanja_aplikacije')
    op.drop_table('podesavanja_aplikacije')
    op.drop_table('knjizno_odobrenje')
    op.drop_index('operater_id', table_name='kalkulacija')
    op.drop_index('magacin_id', table_name='kalkulacija')
    op.drop_index('firma_id', table_name='kalkulacija')
    op.drop_index('dobavljac_id', table_name='kalkulacija')
    op.drop_table('kalkulacija')
    op.drop_index('vrstaplacanja', table_name='faktura')
    op.drop_index('storno_faktura_id', table_name='faktura')
    op.drop_index('naplatni_uredjaj_id', table_name='faktura')
    op.drop_index(op.f('ix_faktura_komitent_id'), table_name='faktura')
    op.drop_index('firma_id', table_name='faktura')
    op.drop_index('brojoperatera', table_name='faktura')
    op.drop_index('IX_DDEF1ED69C9E', table_name='faktura')
    op.drop_index('IX_D5DC1D3EFF98', table_name='faktura')
    op.drop_index('IX_AB073009DB3F', table_name='faktura')
    op.drop_index('IX_6D851962D0F8', table_name='faktura')
    op.drop_table('faktura')
    op.drop_table('payment_device_lock')
    op.drop_table('order_grupa')
    op.drop_index('naplatni_uredjaj_id', table_name='operater')
    op.drop_index('magacin_id', table_name='operater')
    op.drop_index('firma_id', table_name='operater')
    op.drop_table('operater')
    op.drop_index('magacin_id', table_name='magacin_zaliha')
    op.drop_index('artikal_id', table_name='magacin_zaliha')
    op.drop_table('magacin_zaliha')
    op.drop_table('knjizno_odobrenje_redni_broj')
    op.drop_table('invoice_processing_lock')
    op.drop_table('invoice_counter')
    op.drop_index('poslednja_faktura_redni_broj_fakture', table_name='firma_redni_broj_fakture')
    op.drop_index('naplatni_uredjaj_id', table_name='firma_redni_broj_fakture')
    op.drop_table('firma_redni_broj_fakture')
    op.drop_table('credit_note_processing_lock')
    op.drop_table('organizational_unit_settings')
    op.drop_index('organizaciona_jedinica_id', table_name='naplatni_uredjaj')
    op.drop_table('naplatni_uredjaj')
    op.drop_index('magacin_id', table_name='magacin_redni_broj_kalkulacije')
    op.drop_table('magacin_redni_broj_kalkulacije')
    op.drop_table('dospjela_faktura_notifikacija')
    op.drop_table('csv_datoteka')
    op.drop_index('jedinica_mjere_id', table_name='artikal')
    op.drop_index('grupa_artikala_id', table_name='artikal')
    op.drop_table('artikal')
    op.drop_table('soap_permission')
    op.drop_index('firma_id', table_name='organizaciona_jedinica')
    op.drop_index('drzava_id', table_name='organizaciona_jedinica')
    op.drop_table('organizaciona_jedinica')
    op.drop_index('firma_id', table_name='magacin')
    op.drop_table('magacin')
    op.drop_table('komitent_placanje')
    op.drop_index('firma_id', table_name='jedinica_mjere')
    op.drop_table('jedinica_mjere')
    op.drop_index('firma_id', table_name='grupa_artikala')
    op.drop_table('grupa_artikala')
    op.drop_table('faktura_mail_kampanja')
    op.drop_index('firma_id', table_name='dospjela_faktura')
    op.drop_table('dospjela_faktura')
    op.drop_table('csv_obrada_ovlascenje')
    op.drop_table('company_settings')
    op.drop_index('tip_identifikacione_oznake_id', table_name='komitent')
    op.drop_index(op.f('ix_komitent_drzava'), table_name='komitent')
    op.drop_table('komitent')
    op.drop_index('drzava', table_name='firma')
    op.drop_table('firma')
    op.drop_table('vrsta_placanja')
    op.drop_table('valuta')
    op.drop_table('tip_identifikacione_oznake')
    op.drop_table('tax_exemption_reason')
    op.drop_table('soap_user')
    op.drop_table('poreska_stopa')
    op.drop_table('payment_method_type')
    op.drop_table('invoice_item_correction_type')
    op.drop_table('faktura_tip')
    op.drop_table('drzave')
    op.drop_table('csv_obrada')
    op.drop_table('agent_user')
    op.drop_table('administrator')
    # ### end Alembic commands ###
