"""Dodaje tabelu credit_note_iic_ref za univerzalno praćenje fakture knjižnog odobrenja

Revision ID: 002
Revises: 001
Create Date: 2023-12-29 04:37:41.757865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_note_iic_ref',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_note_id', sa.Integer(), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('iic', sa.String(length=32), nullable=False),
    sa.Column('verification_url', sa.String(length=1000), nullable=False),
    sa.Column('issue_datetime', sa.DateTime(), nullable=False),
    sa.Column('total_21', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('total_7', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('total_0', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('total_exempt', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('amount_21', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('amount_7', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('amount_0', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('amount_exempt', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['credit_note_id'], ['knjizno_odobrenje.id'], name='FK_BF33DA39337D'),
    sa.ForeignKeyConstraint(['invoice_id'], ['faktura.id'], name='FK_D27719BCDDF8'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_note_iic_ref')
    # ### end Alembic commands ###
