"""Uklanja tabelufirma_redni_broj_fakture

Revision ID: 003
Revises: 002
Create Date: 2023-12-31 01:27:53.204126

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '003'
down_revision = '002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firma_redni_broj_fakture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firma_redni_broj_fakture',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('godina', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poslednja_faktura_redni_broj_fakture', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('naplatni_uredjaj_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['naplatni_uredjaj_id'], ['naplatni_uredjaj.id'], name='firma_redni_broj_fakture_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
