"""Uklanja tabelu knjizno_odobrenje_redni_broj

Revision ID: 004
Revises: 003
Create Date: 2023-12-31 02:28:25.692194

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '004'
down_revision = '003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knjizno_odobrenje_redni_broj')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knjizno_odobrenje_redni_broj',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('godina', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vrijednost', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('naplatni_uredjaj_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['naplatni_uredjaj_id'], ['naplatni_uredjaj.id'], name='fk__knjizno_odobrenje_redni_broj__naplatni_uredjaj'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
