"""Dorada za upload sertifikata

Revision ID: 006
Revises: 005
Create Date: 2024-03-16 20:30:43.767077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiscalization_certificate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=True),
    sa.Column('not_valid_before', sa.DateTime(), nullable=False),
    sa.Column('not_valid_after', sa.DateTime(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['firma.id'], name='FK_C46E0DE61C29'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('IX_FCDFDCCC7ABA', 'fiscalization_certificate', ['owner_id'], unique=False)
    op.add_column('firma', sa.Column('next_certificate_id', sa.Integer(), nullable=True))
    op.add_column('firma', sa.Column('current_certificate_id', sa.Integer(), nullable=True))
    op.create_foreign_key('FK_A960B5AE8DCC', 'firma', 'fiscalization_certificate', ['next_certificate_id'], ['id'])
    op.create_foreign_key('FK_B53887B9C3E1', 'firma', 'fiscalization_certificate', ['current_certificate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('FK_B53887B9C3E1', 'firma', type_='foreignkey')
    op.drop_constraint('FK_A960B5AE8DCC', 'firma', type_='foreignkey')
    op.drop_column('firma', 'current_certificate_id')
    op.drop_column('firma', 'next_certificate_id')
    # op.drop_index('IX_FCDFDCCC7ABA', table_name='fiscalization_certificate')
    op.drop_table('fiscalization_certificate')
    # ### end Alembic commands ###
